### ISSUE TITLE
Cache resolution fails if file name contains a plus (+)

### ISSUE THREAD

**Issue by sujayjaju** [liip/LiipImagineBundle#1143]
### Preconditions

1. LiipImagineBundle 2.1
2. PHP 7.2

### Steps to reproduce

1. Try resolving a file named "test+file.jpg". Eg:
`{{ "uploads/test+file.jpg" | imagine_filter('thumb') }}`

### Expected result

* Resolved image

### Actual result

* Error" `Source image for path "uploads/test file.jpg" could not be found`

**Comment by sujayjaju** [comment]
Same issue if there is a hash (#) in the file name

**Comment by robfrawley** [comment]
A hash has a special context in a browser; same with a plus. You would need to encode the URL path for it to work properly.

**Comment by sujayjaju** [comment]
@robfrawley 
Yes, but the problem is that the imagine_filter double encodes the file name, if it is encoded name is passed to the filter. The solution that worked was to extract just the file name after filter and replaced it with the encoded version. That seems like quite a convoluted solution. Should the filter handle those cases?

**Comment by torinaki** [comment]
@sujayjaju I have the same issue. The problem is that `\Liip\ImagineBundle\Imagine\Cache\Resolver\ResolverInterface::resolve` method implementations (`WebPathResolver` and probably others) do not expect that file system path [might contain special characters](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits). In case of URL, most of these characters should be encoded.

Probably the proper fix will be to convert filesystem path to URL path in following way:
```php
implode('/', array_map('rawurlencode', explode('/', $path)))
```

**Comment by andyexeter** [comment]
I can confirm @torinaki's solution fixes this issue. Care to submit a PR for this?

**Comment by torinaki** [comment]
@anderageru, @sujayjaju PR is created

**Comment by torinaki** [comment]
Fixed in #1162

**Comment by Seb33300** [comment]
I am still encountering issues with images containing a `+`

In filter action, there is no need to `urldecode` the filename because `+` are decoded as spaces and file is not found.

**Comment by dbalabka** [comment]
@Seb33300 could you please describe your case in detail? It would be great to see the URL and expected file path examples.
