### ISSUE TITLE
Rotation issue

### ISSUE THREAD

**Issue by Merk87** [liip/LiipImagineBundle#532]
Hello.

I'm experiencing a weird bug.
I'm using the thumbnail filters and when my users upload a picture for example this one:
![pic](https://cloud.githubusercontent.com/assets/1273171/5261897/1f89785a-7a1f-11e4-9088-a9e8cd4c6586.jpeg)

Automatically is rotated... I've checked the exif data for this one and in orientation I found
Orientation Rotate 90 CW
So, I'm guessing that the bundle is taking the orientation on the exif data and applying automatically, but this behaviour can be deactivated? Because in this case this image is vertical but after uploading it, the thumbnail is displayed as landscape...

Thanks!

Edit --> After updating the picture here, is also rotated.

**Comment by digitalkaoz** [comment]
you could use the `autorotate` filter which should fix this issue

**Comment by trsteel88** [comment]
Also, make sure you don't run the **strip** filter before **autorotate** or it will remove the meta that tells the filter which direction it should be rotated to.

**Comment by Merk87** [comment]
Nothing I'm still having the same problem... this is my config, because I don't know what else try...

```yml
liip_imagine:
    driver:         imagick
    cache_prefix:   /uploads/cache
    filter_sets:
        profile_view:
            quality: 80
            filters:
                autorotate: ~
                strip: ~
                thumbnail: { size: [178, 178], mode: outbound }
```

**Comment by trsteel88** [comment]
The meta on the image may be forcing it to rotate to what you see. Try it without (you will need to clear your media cache)

**Comment by Merk87** [comment]
@trsteel88 sorry for my ignorance about this, but what you mean when say to clear media cache?

**Comment by trsteel88** [comment]
When an image is loaded it creates a cache in /web/media/cache - You will need to clear that cache if you want to see image based on your latest config.

**Comment by Merk87** [comment]
Ah, yes I always delete the cache when I change the config, but still no working. Anyway thanks very much for your help.

**Comment by bocharsky-bw** [comment]
@digitalkaoz The auto rotate filter's name is `auto_rotate`, it pointed in [docs](http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html#the-auto-rotate-filter)
@Merk87 Try to use `auto_rotate` filter instead of `autorotate`?

**Comment by Ananas85** [comment]
I've got the same problem after upload my Pictures are autorotate by the bundle even if I add the autorotate filter, have you fix it ?

**Comment by Merk87** [comment]
No, but the other day I found the problem. The previous developer (who installed the bundle) use and old version of the liip bundle...

**Comment by Ananas85** [comment]
So, in your opinion, using an old version of this bundle is the only solution ? ^^

**Comment by Merk87** [comment]
Nope, using an old version is the problem! the autorotate filter is called auto_rotate, check your configs.

**Comment by Ananas85** [comment]
I think that i'm using the latest version, there is my config : 

my_portfolio:
            filters:
                auto_rotate: ~
                relative_resize: { scale: 0.5 }    # Transforms 50x40 to 32x26

the auto_rotate doesn't work at time.

And there is the config of the bundle into my composer.json :  "liip/imagine-bundle": "~1.2"

**Comment by digitalkaoz** [comment]
Dump the exif Data of the File here, and we may find the Problem

anaelChardan <notifications@github.com> schrieb am Fr., 17. Apr. 2015 15:18:

**Comment by Ananas85** [comment]
Hum, can you help me to do that please ? :)

**Comment by digitalkaoz** [comment]
http://mikebeach.org/2011/12/17/how-to-retrieve-exif-data-from-the-command-line-in-ubuntu-linux/

anaelChardan <notifications@github.com> schrieb am Fr., 17. Apr. 2015 18:04:

**Comment by Ananas85** [comment]
Here is an example : 

    exif:ApertureValue: 227/100
    exif:BrightnessValue: 973/100
    exif:ColorSpace: 1
    exif:ComponentsConfiguration: 1, 2, 3, 0
    exif:DateTime: 2015:04:01 20:03:29
    exif:DateTimeDigitized: 2015:04:01 20:03:29
    exif:DateTimeOriginal: 2015:04:01 20:03:29
    exif:ExifImageLength: 3096
    exif:ExifImageWidth: 4128
    exif:ExifOffset: 237
    exif:ExifVersion: 48, 50, 50, 48
    exif:ExposureBiasValue: 0/10
    exif:ExposureMode: 0
    exif:ExposureProgram: 2
    exif:ExposureTime: 1/2824
    exif:Flash: 0
    exif:FlashPixVersion: 48, 49, 48, 48
    exif:FNumber: 220/100
    exif:FocalLength: 413/100
    exif:FocalLengthIn35mmFilm: 31
    exif:GPSDateStamp: 2015:04:01
    exif:GPSImgDirection: 95/1
    exif:GPSImgDirectionRef: M
    exif:GPSInfo: 2951
    exif:GPSTimeStamp: 18/1, 3/1, 28/1
    exif:GPSVersionID: 2, 2, 0, 0
    exif:ImageLength: 3096
    exif:ImageWidth: 4128
    exif:InteroperabilityIndex: R98
    exif:InteroperabilityOffset: 2921
    exif:InteroperabilityVersion: 48, 49, 48, 48
    exif:ISOSpeedRatings: 50
    exif:LightSource: 0
    exif:Make: SAMSUNG
    exif:MakerNote: 7, 0, 1, 0, 7, 0, 4, 0, 0, 0, 48, 49, 48, 48, 2, 0, 4, 0, 1, 0, 0, 0, 0, 32, 1, 0, 12, 0, 4, 0, 1, 0, 0, 0, 0, 0, 0, 0, 16, 0, 5, 0, 1, 0, 0, 0, 90, 0, 0, 0, 64, 0, 4, 0, 1, 0, 0, 0, 0, 0, 0, 0, 80, 0, 4, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    exif:MaxApertureValue: 228/100
    exif:MeteringMode: 2
    exif:Model: SM-N9005
    exif:Orientation: 6
    exif:ResolutionUnit: 2
    exif:SceneCaptureType: 0
    exif:SceneType: 1
    exif:SensingMethod: 2
    exif:ShutterSpeedValue: 1146/100
    exif:Software: N9005XXUGBNL8
    exif:UserComment: 65, 83, 67, 73, 73, 0, 0, 0, 10, 0, 0, 0, 74, 75, 74, 75, 39, 8, 170, 60, 247, 3, 1, 0, 150, 4, 1, 0, 0, 0, 0, 0, 220, 218, 1, 0, 0, 0, 1, 0, 34, 131, 1, 0, 0, 0, 0, 0, 0, 119, 11, 0, 0, 0, 4, 0, 0, 187, 9, 0, 184, 21, 0, 0, 90, 248, 1, 0, 0, 0, 1, 0, 250, 141, 1, 0, 85, 248, 1, 0, 0, 0, 1, 0, 186, 142, 1, 0, 45, 236, 1, 0, 38, 251, 254, 255, 173, 24, 0, 0, 97, 186, 255, 255, 107, 153, 1, 0, 52, 172, 255, 255, 97, 2, 0, 0, 205, 36, 255, 255, 210, 216, 1, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 145, 17, 1, 0, 146, 153, 9, 0, 146, 153, 9, 0, 146, 153, 9, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 146, 153, 9, 0, 146, 153, 9, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 146, 153, 9, 0, 146, 153, 9, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 146, 153, 9, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 16, 17, 1, 0, 0, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 146, 153, 9, 0, 2, 136, 8, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 146, 153, 9, 0, 2, 136, 8, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 2, 136, 8, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 17, 34, 2, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 2, 136, 8, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 1, 34, 2, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 2, 136, 8, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 2, 136, 8, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 17, 34, 2, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 2, 136, 8, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 2, 136, 8, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 16, 17, 1, 0, 0, 17, 1, 0, 0, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 1, 34, 2, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 0, 17, 1, 0, 16, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 2, 136, 8, 0, 1, 34, 2, 0, 1, 34, 2, 0, 1, 34, 2, 0, 0, 17, 1, 0, 1, 34, 2, 0, 0, 17, 1, 0, 1, 34, 2, 0, 0, 17, 1, 0, 16, 17, 1, 0, 1, 34, 2, 0, 16, 17, 1, 0, 17, 34, 2, 0, 145, 17, 1, 0, 145, 17, 1, 0, 145, 17, 1, 0, 164, 252, 1, 0, 28, 0, 1, 0, 79, 142, 1, 0, 182, 243, 1, 0, 238, 255, 0, 0, 229, 151, 1, 0, 0, 0
    exif:WhiteBalance: 0
    exif:XResolution: 72/1
    exif:YCbCrPositioning: 1
    exif:YResolution: 72/1
    Profile-exif: 17375 bytes

**Comment by digitalkaoz** [comment]
Mh regarding

exif:Orientation: 6

It should rotate 90°

Isnt that correct?

anaelChardan <notifications@github.com> schrieb am Sa., 18. Apr. 2015 19:29:

**Comment by Ananas85** [comment]
Yep on my Web page my Pictures appears with rotation of 90 so it's not good for the neck of my viewers ^^

**Comment by digitalkaoz** [comment]
But what should we do? We only trust the exif data. If they arent correct
there is nothing we can do?! Maybe a separat Filter without auto_rotate?

anaelChardan <notifications@github.com> schrieb am Sa., 18. Apr. 2015 20:34:

**Comment by Ananas85** [comment]
I don't know, I will try with two separate filters. What is your ideas ? Else, I can add a field in my form to rotate or not the picture. I really don't know :)

**Comment by digitalkaoz** [comment]
I have no idea. It depends ;)

anaelChardan <notifications@github.com> schrieb am Sa., 18. Apr. 2015 20:45:

**Comment by bocharsky-bw** [comment]
The problem is that `auto_rotate` filter should rotate **only** images, which load from mobile devices directly. If user load image from mobile to his laptop first, and then load this image from laptop to the website, this image already rotated by laptop browser and shouldn't rotate by website.

It's probably needs more tests. I tested my image on iPhone and Ubuntu laptop. When I load image directly from iPhone - `auto_rotate` filter work correctly. But when I drop this image to laptop and then from laptop load it to website, image was rotated incorrectly (The correct result was achieved when I turn of `auto_rotate` filter when load image from laptop).

I think we need to modified `AutoRotateFilterLoader` to rotate only images which loads dicrectly from mobile devices. What are you think, guys?

**Comment by digitalkaoz** [comment]
who should modify the exif data during download on your laptop? something in your workflow modifies the exif data...

**Comment by Ananas85** [comment]
I agree with bocharsky, I think it's the source of the problem. I'll try to find a solution tonight.

**Comment by bocharsky-bw** [comment]
@digitalkaoz The exif data not modify during I download image on my laptop. I think laptop browser resolve rotation based on exif data before upload it to website and website get already rotated image, nonetheless the source image on laptop stay not modified.

@Ananas85 Thanks! I will test it idea more thoroughly tomorrow too. And it will be great to test on Mac and Windows OS too.

**Comment by bocharsky-bw** [comment]
I made an prototype that resolved this issue for me and create an PR #599. 
I added new filter loader named `mobile_auto_rotate` . The config should be:

``` yml
liip_imagine:
    filter_sets:
        my_thumb:
            filters:
                mobile_auto_rotate: ~
```

Could anybody test it on yours projects?

P.S. don't forget to use my `mobile_auto_rotate` branch from PR to test.

**Comment by digitalkaoz** [comment]
user agent spoofing cant be trusted, but if it works for you...

so desktop browser have support for auto_rotating images based on the exif data and mobile browser not? or vice versa?

**Comment by Ananas85** [comment]
Hi, first, Thank you @bocharsky-bw , I think it will correct the problem, I just need you to test it into my project, can you help me please. :-)

**Comment by bocharsky-bw** [comment]
@Ananas85 Hi! What help do you need?

**Comment by dutchiexl** [comment]
Does this currently work in the master ?

**Comment by fender-hm** [comment]
I have 1.3.1, and have the same problem

**Comment by alexislefebvre** [comment]
This filter work:

```
                rotate:
                    angle: 270
```

This one doesn't:

```
                auto_rotate: ~
```

It's like the filter is never called.

I use Imagine 0.5.

Maybe the problem comes from the fact that `exif_read_data use in the [AutoRotateFilterLoader](https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Filter/Loader/AutoRotateFilterLoader.php#L97) file expect a file and not a string: http://php.net/manual/en/function.exif-read-data.php

**Comment by robfrawley** [comment]
@alexislefebvre Imagine `0.5` is **really old**. I'd recommend updating at the nearest possible opportunity. We're actively supporting and developing `1.x` and development for `2.x` is underway; the `0.5` branch likely doesn't have a long lifetime moving forward. Just an FYI.

**Comment by alexislefebvre** [comment]
I removed the requirement on the `0.5` version and I was able to update to Imagine `0.6.3`. Now the `auto_rotate` filter works.

Finally, it looks like `auto_rotate` only works with Imagine `~0.6`. Can someone confirm this? It could be explained in the documentation.

**Comment by alexislefebvre** [comment]
I was able to upgrade Imagine to the last version (`0.6.3`) and it works now, the `auto_rotate` is applied. Thanks @robfrawley.

**Comment by robfrawley** [comment]
@alexislefebvre I'll look into inserting a note in the documentation.

**Comment by deivid11** [comment]
auto_rotate wont work if exif PHP function is not enabled

**Comment by florianajir** [comment]
Thank you @deivid11 you saved me from loosing more than a day 😆 
I think it could be great for future user to check if php configuration is matching bundle configuration and throw an exception if not the case.

**Comment by michellesanver** [comment]
Closing this issue because of #1230

More details: https://github.com/liip/LiipImagineBundle/pull/1230#issuecomment-537934662

If it's still an issue for you, please open a new PR, and thanks a lot :)
