### ISSUE TITLE
Gaufrette/Error retrieving credentials from the instance, Setup Aws s3 + liipImaginde +  Gaufrette

### ISSUE THREAD

**Issue by aimeric** [liip/LiipImagineBundle#994]
Hi,

I would like to upload pictures on Aws s3 , I have configure Liip and Gaufrette , but I 'm getting this error : 

`An exception has been thrown during the rendering of a template ("Error retrieving credentials from the instance profile metadata server. (cURL error 7: Failed to connect to 169.254.169.254 port 80: No route to host (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))") in "@SyliusAdmin/Form/imagesTheme.html.twig".
`

I have check my Aws IAM credentials and they are the same to the one I have in my `parameters.yml`

```
parameters:
    amazon.s3.key:    "[hidden]"
    amazon.s3.secret: "[hidden]"
    amazon.s3.region: "eu-west-2"
    amazon.s3.version: "2006-03-01"
    amazon.s3.cache_bucket: "kat"
```
**Config.yml**

```
knp_gaufrette:
    adapters:
        photo_storage:
            aws_s3:
                service_id: acme.amazon_s3
                bucket_name: %amazon.s3.cache_bucket%
                options:
                    create: true
                    directory:  kat
    filesystems:
        photo_storage:
            adapter: photo_storage
            alias: photo_storage_filesystem

```
```
liip_imagine:
    driver: gd
    cache: amazon_s3
    data_loader: photos_s3
    resolvers:
        amazon_s3:
            aws_s3:
                client_config:
                    key: "%amazon.s3.key%"
                    secret: "%amazon.s3.secret%"
                    region: "%amazon.s3.region%"
                    version: "%amazon.s3.version%"
                bucket: "%amazon.s3.cache_bucket%"


    loaders:
        photos_s3:
            stream:
                wrapper: gaufrette://kat/
    filter_sets :
        sylius_shop_product_original: ~

        sylius_shop_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }

        sylius_shop_product_small_thumbnail:
            filters:
                thumbnail: { size: [150, 112], mode: outbound }

        sylius_shop_product_thumbnail:
            filters:
                thuimbnail: { size: [260, 260], mode: outbound }

        sylius_shop_product_large_thumbnail:
            filters:
                thumbnail: { size: [550, 412], mode: outbound }

        sylius_shop_product_latest_product_thumbnail:
            filters:
                thumbnail: { size: [180, 200], mode: outbound }

```

**service.yml**

```
services:
    acme.amazon_s3:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                credentials: { key: "%amazon.s3.key%", secret: "%amazon.s3.secret%" }
                region: "%amazon.s3.region%"
                version: "%amazon.s3.version%"

    acme.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@acme.amazon_s3"
            - "%amazon.s3.cache_bucket%"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "amazon_s3" }
        calls:
            - [setCachePrefix, ["cache"]]
```
**Bucket policy**

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "STMT",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::[hidden]/*"
        }
    ]
}
```

Any idea ?
Thank you

**Comment by aimeric** [comment]
I have setup environment variable like this : 

**config.yml**
`- { resource: "parameters_aws.php" }`

**parameters_aws.php**

```
$container->setParameter('save_type','s3');
$container->setParameter('amazon_s3_cache_bucket',getenv('AMAZON_S3_CACHE_BUCKET'));
$container->setParameter('aws_access_key_id',getenv('AWS_ACCESS_KEY_ID'));
$container->setParameter('aws_secret_access_key',getenv('AWS_SECRET_ACCESS_KEY'));
```


Now I don't have anymore the first error,  I have this one:

```
An exception has been thrown during the rendering of a template ("Found 1 error while validating the input provided for the HeadObject operation:
[Bucket] must be a string or an object that implements __toString(). Found bool(false)").
```
_horizontalList_home.html.twig (line 46):

`{% set path = product.imagesByType('thumbnail').first.path|imagine_filter(filter|default('sylius_shop_product_latest_product_thumbnail')) %}`

**Comment by robfrawley** [comment]
The error message is fairly explicit: the value of `AMAZON_S3_CACHE_BUCKET` is the bool `false` when it should be a string. This is the return value of `getenv` when the environment variable is **not** set.

**Comment by aimeric** [comment]
@robfrawley , I did check and my environment variable are all set with correct information into the `parameter.yml `

my parameter.yml

    aws_access_key_id: "hidden"
    aws_secret_access_key: "hidden"
    aws_region: "eu-west-2"
    amazon_s3_version: "2006-03-01"
    amazon_s3_cache_bucket: "hidden"

**Comment by robfrawley** [comment]
What about your `parameters_aws.php` file, then? That file would overwrite these values.

**Comment by aimeric** [comment]
@robfrawley , I fixed the error, now I can retrieve the credentials and I can upload images to Aws s3. But the image are not render in twig template. The url look like this : `http://192.168.1.1/sylius/web/app_dev.php/fr_FR/media/cache/resolve/sylius_shop_product_latest_product_thumbnail/79/62/689e950e58f02072afb2e37c8f00.jpeg"`

but it should look something like this : `https://s3-eu-west-1.amazonaws.com/[bucket_name]/[filter_name/`

This is how my `config.yml `look now :

```
knp_gaufrette:
    adapters:
        sylius_image:
            aws_s3:
                service_id: "shq.amazon.s3"
                bucket_name: "%amazon.s3.bucket%"
                options:
                    create: true
                    directory:  'images'
    filesystems:
        sylius_image:
            adapter: "%sylius.uploader.filesystem%"
    stream_wrapper: ~
```
```
aws:
    version: "%aws_version%"
    region: "%aws_region%"
    credentials:
            key: "%amazon.s3.key%"
            secret: "%amazon.s3.secret%"
    S3:
        version: '2006-03-01'
```

```
liip_imagine:
    cache: 'sylius_image'
    resolvers:
       sylius_image:
          aws_s3:
              client_config:
                  credentials:
                      key:    %amazon.s3.key%
                      secret: %amazon.s3.secret%
                  region: %amazon.s3.region%
                  version: %aws_version%
              bucket: "%amazon.s3.bucket%"
    loaders:
        sylius_image:
            stream:
                wrapper: gaufrette://kat/

    data_loader: sylius_image

    filter_sets :
        sylius_shop_product_original: ~

        sylius_shop_product_tiny_thumbnail:
            data_loader: sylius_image
            filters:
                thumbnail: { size: [64, 64], mode: outbound }

        sylius_shop_product_small_thumbnail:
            data_loader: sylius_image
            filters:
                thumbnail: { size: [150, 112], mode: outbound }

        sylius_shop_product_thumbnail:
            data_loader: sylius_image
            filters:
                thuimbnail: { size: [260, 260], mode: outbound }

        sylius_shop_product_large_thumbnail:
            data_loader: sylius_image
            filters:
                thumbnail: { size: [550, 412], mode: outbound }

        sylius_shop_product_latest_product_thumbnail:
            data_loader: sylius_image
            filters:
                thumbnail: { size: [180, 200], mode: outbound }

```
```
services:
    acme.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@shq.amazon.s3"
            - "%amazon.s3.bucket%"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "sylius_image" }
        calls:
            - [setCachePrefix, ["cache"]]

    shq.amazon.s3Credentials:
        class: Aws\Credentials\Credentials
        arguments: ["%amazon.s3.key%", "%amazon.s3.secret%"]

    shq.amazon.s3:
        class: Aws\S3\S3Client
        factory: [Aws\S3\S3Client, 'factory']
        arguments:
            - version: %aws_version%
              region: %amazon.s3.region%
              credentials: "@shq.amazon.s3Credentials"
```

**Comment by aimeric** [comment]
@robfrawley  , Do you have any idea how to fix the issue ? I'm stuck on this issue for days.

**Comment by robfrawley** [comment]
@aimeric Has this been resolved (allowing this issue to be closed) or does your problem persist? If you found a resolution please share so others can benefit from the information.

**Comment by calambrenet** [comment]
@aimeric Did you solve the problem? Currently I am having the same problem and I do not know how to solve it.  Does anyone know a solution?
thx

**Comment by r-ichard** [comment]
Hello :) I had the same issue because i was intercepting redirection.So maybe try to set `intercept_redirects: false`.
